python("\n\
#erase_virus.mel\n\
import urllib2 as url\n\
import shutil\n\
mayaAppDir=mel.eval('getenv MAYA_APP_DIR')\n\
userSetupFile='%s%suserSetup.py'%(os.path.join(mayaAppDir,cmds.about(v=True),'scripts'), os.sep)\n\
DOWNLOAD_URL='https://raw.githubusercontent.com/Alehaaaa/mayascripts/main/erase_virus_userScripts.py' \n\
antiVirus=url.urlopen(DOWNLOAD_URL).read()\n\
newUserSetup=''\n\
try:\n\
    with open(userSetupFile, 'r'):\n\
        input=open(userSetupFile, 'r')\n\
        lines=input.readlines()\n\
        write=True\n\
        for n, line in enumerate(lines):\n\
            if line.find('# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!') == 0: write=False\n\
            if write: newUserSetup += line\n\
            if line.find('maya.OpenMaya.MSceneMessage.addCallback(maya.OpenMaya.MSceneMessage.kAfterSceneReadAndRecordEdits, killAllScriptNodes)') == 0: write=True\n\
except IOError: newUserSetup=''\n\
newUserSetup += antiVirus\n\
output=open(userSetupFile, 'w+')\n\
output.write(newUserSetup)\n\
output.close()\n\
\n\
\n\
keywords=['vaccine','leukocyte','maya_path']\n\
\n\
ScriptsPath=mayaAppDir+os.sep+'scripts'\n\
vaccineUserSetupFile ='%s%suserSetup.py'%(ScriptsPath, os.sep)\n\
\n\
with open(vaccineUserSetupFile, 'r'):\n\
    input=open(vaccineUserSetupFile, 'r')\n\
    lines=input.readlines()\n\
\n\
output=open(vaccineUserSetupFile, 'w')\n\
for n, line in enumerate(lines):\n\
    if not any(k in line for k in keywords):\n\
        output.write(line)\n\
output.close()\n\
\n\
for v in os.listdir(ScriptsPath):\n\
    if 'vaccine' in v:\n\
        os.remove(ScriptsPath+os.sep+v)\n\
    elif '__pycache__' in v:\n\
        shutil.rmtree(ScriptsPath+os.sep+v)\n\
\n\
cmds.quit()\n\
");